"use strict";

const app=document.querySelector("#app"),E=CafeteriaEngine.event;
let state=CafeteriaEngine.create(),activePresentation=null,inputLocked=false,presentationTimer=null,presentationQueue=[];
const button=(label,action,disabled=false,description="",primary=false)=>`<button type="button" class="action-button ${primary?"primary":""}" data-action="${action}" ${disabled||inputLocked?"disabled":""}><strong>${label}</strong>${description?`<small>${description}</small>`:""}</button>`;

const ICON_PATHS={hwayoung:"assets/icons/hwayoung.png","kang-unshim":"assets/icons/kang-unshim.png","epi-minos":"assets/icons/epi-minos.png",inan:"assets/icons/inan.png","kim-wooju":"assets/icons/kim-wooju.png",mageuna:"assets/icons/mageuna.png","byeon-ari":"assets/icons/byeon-ari.png",josangmin:"assets/icons/josangmin.png","jegal-mina":"assets/icons/jegal-mina.png"};
const iconMarkup=(id,className="char-icon")=>ICON_PATHS[id]?`<img class="${className}" src="${ICON_PATHS[id]}" alt="" aria-hidden="true">`:"";
const MINA_THEME_PATH="assets/jegal-mina-theme.css";
if(!document.querySelector('link[data-seonga-jegal-mina-theme]')){const link=document.createElement("link");link.rel="stylesheet";link.href=MINA_THEME_PATH;link.dataset.seongaJegalMinaTheme="";document.head.append(link);}

const cast=()=>[...state.partyIds,state.supportId].filter((id,index,all)=>all.indexOf(id)===index);

function presentationMarkup(){
  if(!activePresentation)return"";
  const x=activePresentation,kind=x.type||"narration",commonTone=["damage","danger","success","warning"].includes(x.tone),accentId=x.accent||(!commonTone&&E.characterPool.includes(x.source)?x.source:""),accent=accentId?` accent-${accentId}`:"",tone=x.tone?` tone-${x.tone}`:"",body=kind==="effect"&&x.items?`<ul>${x.items.map(item=>`<li>${item.text}</li>`).join("")}</ul>`:`<strong>${kind==="dialogue"?`“${x.text}”`:x.text}</strong>`;
  return`<aside class="presentation-layer ${kind}${accent}${tone}" aria-live="assertive">${kind==="dialogue"?iconMarkup(accentId,"presentation-watermark"):""}<span class="presentation-kind">${kind==="dialogue"?x.speaker:kind==="effect"?"RESULT":"SCENE"}</span><div class="presentation-body">${body}</div><button type="button" class="presentation-next" data-action="presentation-next">${kind==="dialogue"?"계속":"빠르게 넘기기"} <b>›</b></button></aside>`;
}
function render(){const views={party:renderParty,briefing:renderBriefing,exploration:renderExploration,battle:renderBattle,interlude:renderInterlude,success:renderResult,failure:renderResult};app.innerHTML=presentationMarkup()+views[state.phase]();}
function bundlePresentation(events){const bundled=[];for(const item of events){const previous=bundled[bundled.length-1];if(item.type==="effect"&&previous?.type==="effect"){previous.items.push(item);previous.text=previous.items.map(x=>x.text).join(" · ");if(["danger","damage"].includes(item.tone))previous.tone=item.tone;}else bundled.push(item.type==="effect"?{...item,items:[item]}:item);}return bundled;}
function presentationDelay(item){return item.type==="narration"?720:560;}
function advancePresentation(){if(presentationTimer)clearTimeout(presentationTimer);presentationTimer=null;if(!presentationQueue.length){activePresentation=null;inputLocked=false;render();return;}activePresentation=presentationQueue.shift();render();if(activePresentation.type!=="dialogue")presentationTimer=setTimeout(advancePresentation,presentationDelay(activePresentation));}
function playPresentation(){
  presentationQueue.push(...bundlePresentation(CafeteriaEngine.takePresentation(state)));
  if(window.SEONGA_TEST_INSTANT_PRESENTATION){presentationQueue.length=0;activePresentation=null;inputLocked=false;render();return;}
  if(inputLocked||!presentationQueue.length){render();return;}
  inputLocked=true;advancePresentation();
}
function flushPresentation(){if(presentationTimer)clearTimeout(presentationTimer);presentationQueue.length=0;CafeteriaEngine.takePresentation(state);activePresentation=null;inputLocked=false;render();}

function renderParty(){
  const pool=E.characterPool.map(CafeteriaEngine.character),support=CafeteriaEngine.character(state.supportId);
  const roster=pool.map((c,i)=>{const selected=state.partyIds.includes(c.id),rear=c.id===state.supportId;return`<button type="button" class="roster-row accent-${c.id} ${selected?"selected":""} ${rear?"rear":""}" data-action="toggle:${c.id}" aria-pressed="${selected}" ${inputLocked?"disabled":""}><span class="roster-index">${String(i+1).padStart(2,"0")}</span><span class="roster-emblem">${iconMarkup(c.id,"roster-icon")}</span><span class="roster-name"><strong>${c.name}</strong><small>${c.game.position}열 · ${c.game.role}</small></span><span class="roster-state">${selected?"출전":"대기"}</span></button>`;}).join("");
  const rear=pool.filter(c=>!state.partyIds.includes(c.id)).map(c=>`<button type="button" class="support-pick accent-${c.id} ${c.id===state.supportId?"selected":""}" data-action="support-select:${c.id}" ${inputLocked?"disabled":""}><strong class="icon-label">${iconMarkup(c.id,"support-pick-icon")}<span>${c.name}</span></strong><small>${E.supportAdapters[c.id].label}</small></button>`).join("");
  return`<main class="formation-screen"><header class="screen-heading"><p class="chapter">INCIDENT 02 · DEPLOYMENT</p><h1>급식동에 데려갈 네 명</h1><p>명단을 눌러 출전을 정하고, 남은 인원 가운데 후방 담당을 지정한다.</p></header><div class="formation-layout"><section class="roster-list" aria-label="출전 명단">${roster}</section><aside class="formation-summary"><p class="eyebrow">CURRENT UNIT · ${state.partyIds.length}/${E.rules.partySize}</p><div class="party-ribbon">${state.partyIds.map((id,i)=>`<span class="accent-${id}">${iconMarkup(id,"ribbon-icon")}<b>${i+1}</b>${CafeteriaEngine.character(id).name}</span>`).join("")}</div><p class="eyebrow">REAR SUPPORT</p><div class="support-picks">${rear}</div><p class="support-brief accent-${support.id}"><strong class="icon-label">${iconMarkup(support.id,"label-icon")}<span>${support.name}</span></strong>${E.supportAdapters[support.id].description}</p>${button("편성 확정", "briefing",state.partyIds.length!==E.rules.partySize,"브리핑으로 이동한다.",true)}</aside></div></main>`;
}

function renderBriefing(){return`<main class="story-screen"><p class="chapter">INCIDENT 02 · BRIEFING</p><h1>${E.title}</h1><p class="story-copy">${E.briefing}</p><div class="dialogue-list compact">${cast().map(id=>{const c=CafeteriaEngine.character(id);return`<blockquote class="accent-${id} ${id===state.supportId?"off-field":""}">${iconMarkup(id,"speaker-watermark")}<strong class="speaker-tag"><span>${c.name}${id===state.supportId?" · 후방":""}</span></strong><span>“${E.dialogue.briefing[id]}”</span></blockquote>`;}).join("")}</div><footer class="story-command">${button("사전 조사 시작 →","begin-explore",false,"",true)}</footer></main>`;}

function renderExploration(){
  if(state.selectedLocation){
    const location=E.investigations.find(x=>x.id===state.selectedLocation);
    return`<main class="investigation-screen approach-stage"><header class="screen-heading"><p class="chapter">FIELD APPROACH · ${E.rules.investigationLimit-state.investigationsLeft+1}/${E.rules.investigationLimit}</p><h1>${location.label}</h1><p>${location.prompt}</p></header><p class="approach-prompt">누가, 어떤 방식으로 흔적을 좁힐까?</p><div class="approach-list">${location.choices.map(choice=>{const c=CafeteriaEngine.character(choice.owner);return`<button type="button" class="approach-choice accent-${c.id}" data-action="investigate:${choice.id}" ${inputLocked?"disabled":""}><span class="approach-who">${iconMarkup(c.id,"approach-icon")}<span>${c.name}</span></span><strong>${choice.label}</strong><span>${choice.approach}</span><em>예상 · ${choice.expectation}</em></button>`;}).join("")}</div><nav class="quiet-command">${button("← 다른 장소 보기","leave-location")}</nav></main>${renderLog()}`;
  }
  const available=E.investigations.filter(x=>!state.investigated.includes(x.id)),clues=state.clues.length?state.clues.map(id=>`<li><strong>${E.clueInfo[id].label}</strong><span>${E.clueInfo[id].result}</span></li>`).join(""):"<li class=\"muted\">아직 확보한 결과가 없다.</li>";
  return`<main class="investigation-screen location-stage"><header class="screen-heading"><p class="chapter">INCIDENT 02 · SURVEY</p><h1>검은 거품이 시작된 곳</h1><p>서로 다른 두 장소만 살필 수 있다. 먼저 현장을 고른다.</p></header><div class="investigation-meter"><strong>남은 조사 <b>${state.investigationsLeft}</b>회</strong><span>${state.investigated.map(id=>E.investigations.find(x=>x.id===id).label).join(" · ")||"조사 전"}</span></div><div class="scene-list">${available.map((x,i)=>`<button type="button" class="scene-choice" data-action="select-location:${x.id}" ${state.investigationsLeft<=0||inputLocked?"disabled":""}><span>${String(i+1).padStart(2,"0")}</span><strong>${x.label}</strong><small>${x.prompt}</small><i>살펴보기 →</i></button>`).join("")}</div><aside class="evidence-strip"><p class="eyebrow">FOUND EVIDENCE</p><ul>${clues}</ul></aside><footer class="story-command">${button("급식동 진입 →","start",state.investigated.length!==E.rules.investigationLimit,state.investigated.length!==E.rules.investigationLimit?"서로 다른 장소 두 곳을 조사해야 한다.":"",true)}</footer></main>${renderLog()}`;
}

function memberResource(id,m){if(id==="hwayoung")return`열량 ${m.heat}`;if(id==="kang-unshim")return`정보 ${m.info}`;if(id==="epi-minos")return`보존 ${m.memory}`;if(id==="inan"||id==="kim-wooju")return m.cool?"재정비":"능력 준비";if(id==="mageuna")return`집행 ${m.rules}/3`;if(id==="josangmin")return`비축 ${m.effort}`;return"침식 주의";}
function commandMarkup(actor,actions){const abilities=new Set((E.abilities[actor.id]||[]).map(a=>a.id));return actions.map(a=>{const isAbility=abilities.has(a.id);return`<button type="button" class="action-button accent-${actor.id} ${isAbility?"ability-command":"field-command"}" data-action="act:${a.id}" ${a.disabled||inputLocked?"disabled":""}>${isAbility?iconMarkup(actor.id,"command-character-icon"):""}<span class="command-copy"><strong>${a.label}</strong><small>${a.description}</small></span></button>`;}).join("");}
function objectiveMarkup(){if(state.stage===1&&!state.priority)return`<strong>먼저 지킬 대상을 결정하라</strong><span>${CafeteriaEngine.priorityAvailable(state,"supplies")?"창고 조사로 식자재 보존 경로 해금":"식자재 보존 경로 잠김 · 창고 조사 필요"}</span>`;const o=CafeteriaEngine.objectiveInfo(state);let text=`<strong>${o.primaryLabel} <b>${state.progress}/${o.primaryNeeded}</b></strong>`;if(state.stage===1)text+=`<span>${o.secondaryLabel} ${state.secondary}/${o.secondaryNeeded}${o.secondaryRequired?" · 완료 필수":" · 선택 목표"}</span>`;if(state.stage===2)text+=`<span>사전 고정은 행동 1회를 쓰고 반동을 낮춘다.</span>`;return text;}
function renderBattle(){
  const stage=E.stages[state.stage],actor=CafeteriaEngine.character(state.order[state.turn]),support=CafeteriaEngine.character(state.supportId),pattern=CafeteriaEngine.currentPattern(state),nextPattern=E.patterns[(state.round+(state.stage===0?1:0))%E.patterns.length];
  const party=state.partyIds.map(id=>{const c=CafeteriaEngine.character(id),m=state.members[id],width=Math.round(m.hp/c.game.hp*100);return`<div class="member accent-${id} ${id===actor.id?"active":""} ${m.hp===0?"incapacitated":""}"><strong class="member-name">${iconMarkup(id,"member-icon")}<span>${c.name}${m.hp===0?" · 전투 불능":""}</span></strong><div class="hp-bar"><i style="width:${width}%"></i></div><small>${m.hp}/${c.game.hp} HP · <b class="resource-value">${memberResource(id,m)}</b></small></div>`;}).join("");
  const routes=state.stage===2?`<section class="field-state"><p class="eyebrow">SEALING ROUTES</p><div class="route-line">${state.routes.map(r=>{const target=state.routes.find(x=>x.id===r.agitates),chain=!r.sealed&&target&&!target.sealed?` → ${target.label} 위험 +2`:"";return`<div class="route ${r.sealed?"sealed":""}"><strong>${r.label}</strong><span>${r.sealed?"봉쇄 완료":`위험 ${r.currentRisk}${r.prepared?" · 고정됨":""}${chain}`}</span></div>`;}).join("")}</div></section>`:"";
  const supportAdapter=E.supportAdapters[state.supportId],supportStatus=CafeteriaEngine.supportStatus(state),supportRule=state.supportId==="mageuna"?` · 집행 ${state.members.mageuna.rules}/3`:"";
  return`<main class="combat-screen ${state.spread>=6?"high-threat":""}"><div class="stage-track">${E.stages.map((x,i)=>`<span class="${i===state.stage?"current":i<state.stage?"done":""}">${i+1}. ${x.title}</span>`).join("")}</div><header class="actor-focus accent-${actor.id}">${iconMarkup(actor.id,"actor-watermark")}<div class="actor-copy"><p>${stage.title} · ROUND ${state.round}</p><h1>${actor.name}</h1><span>${actor.game.role} · 행동을 선택한다</span></div></header><section class="danger-line"><div><span>확산도</span><strong>${state.spread}<small>/${E.rules.failureSpread}</small></strong></div><p><b>${pattern.label}</b>${pattern.description}${state.repeatCount>1?` · 직전 ${CafeteriaEngine.character(state.lastActionActorId).name} 동일 행동 ${state.repeatCount}회`:""}<small>다음 반응 · ${nextPattern.label}</small></p><div><span>남은 시간</span><strong>${state.time}</strong></div></section><section class="mission-line"><p class="eyebrow">IMMEDIATE OBJECTIVE</p>${objectiveMarkup()}${state.blockEffect?`<em>${state.blockEffect.label} · 반동 차단 대기</em>`:""}</section><section class="command-section accent-${actor.id}"><p class="eyebrow">COMMAND</p><div class="command-menu">${commandMarkup(actor,CafeteriaEngine.actions(state))}</div></section>${routes}<section class="party-status"><p class="eyebrow">FIELD UNIT</p><div class="party-status-rail">${party}</div></section><section class="support-call accent-${support.id}"><div><p class="eyebrow">REAR SUPPORT · 사건 전체 ${state.supportUses}/${E.rules.supportCharges}${supportRule}</p><strong class="icon-label">${iconMarkup(support.id,"support-icon")}<span>${support.name} · ${supportAdapter.label}</span></strong><span>${supportAdapter.description}</span><small>${supportStatus.available?"지금 연결 가능":supportStatus.reason}</small></div>${button("후방 지원 요청","support",!supportStatus.available)}</section></main>${renderLog()}`;
}

function renderInterlude(){const finished=E.stages[state.stage],next=E.stages[state.stage+1],lines=CafeteriaEngine.transitionDialogue(state),consequence=state.stage===1?`<div class="scene-consequence"><span>조리원 · 안전 확보</span><span>식자재 · ${state.outcomes.supplies==="preserved"?"보존":"오염 손실"}</span></div>`:"";return`<main class="transition-screen"><p class="chapter">${finished.title} · COMPLETE</p><h1>${state.stage===0?"거품이 두 갈래로 갈라진다":"마지막 세 경로가 드러난다"}</h1><p>${next.intro}</p>${consequence}<div class="dialogue-list compact">${lines.map(x=>`<blockquote class="accent-${x.id}">${iconMarkup(x.id,"speaker-watermark")}<strong class="speaker-tag"><span>${CafeteriaEngine.character(x.id).name}</span></strong><span>“${x.text}”</span></blockquote>`).join("")}</div>${button(`${next.title} →`,"next",false,"",true)}</main>${renderLog()}`;}
function renderResult(){const success=state.phase==="success";if(success&&window.CampaignProgress)CampaignProgress.complete(E.id,`두 번째 사건 해결 · ${E.priorities[state.priority].label} · 식자재 ${state.outcomes.supplies==="preserved"?"보존":"손실"}`);const resultText=success?`조리원 전원 안전 · 식자재 ${state.outcomes.supplies==="preserved"?"보존 완료":"일부 오염 손실"} · ${state.routeOrder.map(id=>state.routes.find(r=>r.id===id).label).join(" → ")}`:state.failureReason;return`<main class="ending-screen ${success?"success":"failure"}"><p class="chapter">INCIDENT RESULT</p><h1>${success?"급식동 봉쇄 완료":"대응 실패"}</h1><p class="result-line">${resultText}</p>${success?`<div class="dialogue-list compact">${cast().map(id=>`<blockquote class="accent-${id} ${id===state.supportId?"off-field":""}">${iconMarkup(id,"speaker-watermark")}<strong class="speaker-tag"><span>${CafeteriaEngine.character(id).name}${id===state.supportId?" · 후방":""}</span></strong><span>“${E.dialogue.ending[id]}”</span></blockquote>`).join("")}</div>`:""}<dl class="result-stats"><div><dt>구간별 행동</dt><dd>${state.stageActions.join(" · ")}</dd></div><div><dt>총 행동</dt><dd>${state.stageActions.reduce((a,b)=>a+b,0)}</dd></div><div><dt>남은 지원</dt><dd>${state.supportUses}</dd></div></dl><nav class="ending-commands"><a class="action-button" href="index.html"><strong>지도부실로</strong></a>${button("다른 선택으로 재시작","reset",false,"",true)}</nav></main>${renderLog()}`;}

function logItem(x){const type=x.type||"narration",commonTone=["damage","danger","success","warning","recover","guard"].includes(x.tone),accentId=x.accent||(!commonTone&&E.characterPool.includes(x.source)?x.source:""),accent=accentId?` accent-${accentId}`:"",tone=x.tone?` tone-${x.tone}`:"";if(type==="dialogue")return`<li class="dialogue${accent}${tone}"><strong>${x.speaker}</strong><span>“${x.text}”</span></li>`;return`<li class="${type}${accent}${tone}"><span>${x.text||x.message}</span></li>`;}
function renderLog(){return`<details class="log-panel"><summary>대응 기록 <small>${state.log.length}건 · 펼쳐 보기</small></summary><ol>${state.log.slice().reverse().map(logItem).join("")}</ol></details>`;}

app.addEventListener("click",event=>{let target=event.target;while(target&&target!==app&&!target.dataset.action)target=target.parentElement;if(!target||target===app)return;const [type,id]=target.dataset.action.split(":");if(type==="presentation-next"&&inputLocked){advancePresentation();return;}if(inputLocked)return;let changed=false;if(type==="toggle")changed=CafeteriaEngine.toggle(state,id);if(type==="support-select")changed=CafeteriaEngine.support(state,id);if(type==="briefing")changed=CafeteriaEngine.beginBriefing(state);if(type==="begin-explore")changed=CafeteriaEngine.beginExplore(state);if(type==="select-location")changed=CafeteriaEngine.selectLocation(state,id);if(type==="leave-location")changed=CafeteriaEngine.leaveLocation(state);if(type==="investigate")changed=CafeteriaEngine.investigate(state,id);if(type==="start")changed=CafeteriaEngine.start(state);if(type==="next")changed=CafeteriaEngine.nextStage(state);if(type==="act")changed=CafeteriaEngine.act(state,id);if(type==="support")changed=CafeteriaEngine.useSupport(state);if(type==="reset"){state=CafeteriaEngine.create();changed=true;}if(changed)playPresentation();else render();});
window.SEONGA_CAFETERIA_UI_DEBUG={isLocked:()=>inputLocked,getState:()=>state,flushPresentation};
render();
