"use strict";

const root=document.querySelector("#debug-app"),adapters=SEONGA_DEBUG_ADAPTERS;
let eventId="endless-classroom",adapter=adapters[eventId],state=adapter.create();
const character=id=>SEONGA_CHARACTERS.find(x=>x.id===id);
const button=(label,action)=>SEONGA_UI.button(label,action);
const nestedValue=(object,path)=>path.split(".").reduce((value,key)=>value?.[key],object);
function setNested(object,path,value){const keys=path.split("."),last=keys.pop(),target=keys.reduce((item,key)=>item[key],object);target[last]=value;}
function metricKeys(){const keys=[...adapter.metrics];if(state.magnum)keys.push("magnum.hp","magnum.instability");for(const id of state.partyIds||[])keys.push(`members.${id}.hp`);return keys;}
function render(){const pool=adapter.event.characterPool,party=state.partyIds||[],support=state.supportId||GameEngine.absentId?.(state)||"";root.innerHTML=`<main class="story-screen"><p class="chapter">DEVELOPER TOOL · DIRECT URL ONLY</p><h1>사건 상태 점검</h1><div class="approach-grid">${Object.entries(adapters).map(([id,x])=>`<button class="action-button ${id===eventId?"primary":""}" data-action="event:${id}"><strong>${x.label}</strong><small>${x.event.title}</small></button>`).join("")}</div><section class="panel"><p class="eyebrow">FORMATION</p><div class="support-picks">${pool.map(id=>`<button class="support-pick ${party.includes(id)?"selected":""}" data-action="party:${id}"><strong>${character(id).name}</strong><small>${party.includes(id)?"출전":"대기"}</small></button>`).join("")}</div>${"supportId" in state?`<label>후방 지원 <select data-change="support">${pool.filter(id=>!party.includes(id)).map(id=>`<option value="${id}" ${id===support?"selected":""}>${character(id).name}</option>`).join("")}</select></label>`:"<p>사건 01은 출전에서 빠진 인원이 후방 지원을 담당한다.</p>"}</section><section class="panel"><p class="eyebrow">INVESTIGATION REWARD</p><div class="approach-grid">${adapter.event.investigations.map(location=>location.choices.map(choice=>`<button class="action-button" data-action="investigate" data-location="${location.id}" data-choice="${choice.id}"><strong>${location.label}</strong><small>${character(choice.owner).name} · ${choice.label||choice.approach}</small></button>`).join("")).join("")}</div></section><section class="panel"><p class="eyebrow">STATE CONTROL</p><div class="command-menu">${button("초기 상태","reset")}${button("조사 완료·전투 진입","battle")}${button("현재 행동 1회 실행","act")}${adapter.bossAction?button("보스 행동 실행","boss"):""}${button("성공 상태","success")}${button("실패 상태","failure")}</div><label>Phase <select data-change="phase">${adapter.phaseOptions.map(x=>`<option ${state.phase===x?"selected":""}>${x}</option>`).join("")}</select></label><div class="command-menu">${metricKeys().map(key=>`<label>${key}<input type="number" data-metric="${key}" value="${nestedValue(state,key)??0}"></label>`).join("")}</div></section><section class="panel"><p class="eyebrow">CAMPAIGN STORAGE · EXPLICIT ACTIONS</p><div class="command-menu">${button("해금 초기화","clear-save")}${CampaignProgress.eventCatalog.map(x=>button(`${x.number} 완료 기록`, `complete:${x.id}`)).join("")}</div></section><section class="panel"><p class="eyebrow">CURRENT STATE JSON</p><pre>${JSON.stringify(state,null,2)}</pre></section></main>`;}
function reset(){adapter=adapters[eventId];state=adapter.create();render();}
root.addEventListener("click",event=>{const target=event.target.closest("[data-action]");if(!target)return;const [action,id]=target.dataset.action.split(":");if(action==="event"){eventId=id;reset();return;}if(action==="party"){const party=state.partyIds,index=party.indexOf(id);if(index>=0&&party.length>1)party.splice(index,1);else if(index<0&&party.length<(adapter.event.rules.partySize||4))party.push(id);if(state.supportId&&party.includes(state.supportId))state.supportId=adapter.event.characterPool.find(x=>!party.includes(x));render();return;}if(action==="investigate"){adapter.applyInvestigation(state,target.dataset.location,target.dataset.choice);render();return;}if(action==="reset")reset();if(action==="battle"){state=adapter.create();adapter.enterBattle(state);render();}if(action==="act"){const actions=adapter.engine.availableActions?.(state)||adapter.engine.actions?.(state)||[];const choice=actions.find(x=>!x.disabled);if(choice)(adapter.engine.act||(()=>false))(state,choice.id);render();}if(action==="boss"&&adapter.bossAction){adapter.bossAction(state);render();}if(action==="success"){state.phase="success";render();}if(action==="failure"){state.phase="failure";state.failureReason="디버그 프리셋";render();}if(action==="clear-save"){localStorage.removeItem(CampaignProgress.key);render();}if(action==="complete"){CampaignProgress.complete(id);render();}});
root.addEventListener("change",event=>{if(event.target.dataset.change==="phase"){state.phase=event.target.value;render();}if(event.target.dataset.change==="support"){state.supportId=event.target.value;render();}if(event.target.dataset.metric){setNested(state,event.target.dataset.metric,Number(event.target.value));render();}});
window.SEONGA_DEBUG={getState:()=>state,selectEvent:id=>{if(adapters[id]){eventId=id;reset();}return state;}};
render();
