"use strict";
const hub=document.querySelector("#hub"),progress=CampaignProgress.load(),firstDone=progress.completed.includes("endless-classroom"),secondDone=progress.completed.includes("cafeteria-containment"),thirdDone=progress.completed.includes("library-reality-audit");
const unlocked=CampaignProgress.unlockedCharacterIds().map(id=>SEONGA_CHARACTERS.find(c=>c.id===id)).filter(Boolean);
const ICON_PATHS={hwayoung:"assets/icons/hwayoung.png","kang-unshim":"assets/icons/kang-unshim.png","epi-minos":"assets/icons/epi-minos.png",inan:"assets/icons/inan.png","kim-wooju":"assets/icons/kim-wooju.png",mageuna:"assets/icons/mageuna.png","byeon-ari":"assets/icons/byeon-ari.png",josangmin:"assets/icons/josangmin.png","jegal-mina":"assets/icons/jegal-mina.png"};
const iconMarkup=id=>ICON_PATHS[id]?`<img class="hub-character-watermark" src="${ICON_PATHS[id]}" alt="" aria-hidden="true">`:"";
const MINA_THEME_PATH="assets/jegal-mina-theme.css";
if(!document.querySelector('link[data-seonga-jegal-mina-theme]')){const link=document.createElement("link");link.rel="stylesheet";link.href=MINA_THEME_PATH;link.dataset.seongaJegalMinaTheme="";document.head.append(link);}


hub.innerHTML=`<section class="panel"><h2>사건 대응</h2><div class="approach-grid"><article class="approach-card"><p class="chapter">사건 01 · ${firstDone?"완료":"진행 가능"}</p><h3>방과 후의 끝나지 않는 수업</h3><p>반복 현상 속 학생을 보호하고 원인을 복원한 뒤 안전하게 이탈시킨다.</p><a class="action-button primary" href="tutorial.html">${firstDone?"다시 대응":"사건 시작"}</a></article><article class="approach-card ${firstDone?"":"locked"}"><p class="chapter">사건 02 · ${secondDone?"완료":firstDone?"진행 가능":"잠김"}</p><h3>검은 거품이 넘치는 급식동</h3><p>제한 시간 안에 오염 경로를 분류하고, 서로 충돌하는 구역 목표의 우선순위를 정한다.</p>${firstDone?`<a class="action-button primary" href="cafeteria.html">${secondDone?"다시 대응":"사건 시작"}</a>`:'<p class="hint">첫 사건을 해결하면 개방됩니다.</p>'}</article><article class="approach-card ${secondDone?"":"locked"}"><p class="chapter">사건 03 · ${thirdDone?"완료":secondDone?"진행 가능":"잠김"}</p><h3>존재하지 않는 도서관 정상 운영 안내</h3><p>세 종류의 증거를 대조하고, 덮어쓴 현실을 원래 사실에 다시 고정한다.</p>${secondDone?`<a class="action-button primary" href="library.html">${thirdDone?"다시 대응":"사건 시작"}</a>`:'<p class="hint">두 번째 사건을 해결하면 개방됩니다.</p>'}</article></div></section><section class="panel"><h2>대응 인원 · ${unlocked.length}명</h2><div class="character-grid">${unlocked.map(c=>`<article class="character-card accent-${c.id}">${iconMarkup(c.id)}<div class="character-card-head"><div><h3>${c.name}</h3><p class="role">${c.game.role}</p></div></div><p>${SEONGA_NEUTRAL_KITS[c.id].principle}</p>${firstDone&&SEONGA_UNLOCKS[c.id]?`<p class="source">해금: ${SEONGA_UNLOCKS[c.id].name}<br>${SEONGA_UNLOCKS[c.id].description}</p>`:""}</article>`).join("")}</div></section>`;
