"use strict";

const app=document.querySelector("#app"),E=LibraryEngine.event;
let state=LibraryEngine.create(),activePresentation=null,inputLocked=false,presentationTimer=null,presentationQueue=[];
const button=(label,action,disabled=false,description="",primary=false)=>`<button type="button" class="action-button ${primary?"primary":""}" data-action="${action}" ${disabled||inputLocked?"disabled":""}><strong>${label}</strong>${description?`<small>${description}</small>`:""}</button>`;
const ICON_PATHS={hwayoung:"assets/icons/hwayoung.png","kang-unshim":"assets/icons/kang-unshim.png","epi-minos":"assets/icons/epi-minos.png",inan:"assets/icons/inan.png","kim-wooju":"assets/icons/kim-wooju.png",mageuna:"assets/icons/mageuna.png","byeon-ari":"assets/icons/byeon-ari.png",josangmin:"assets/icons/josangmin.png","jegal-mina":"assets/icons/jegal-mina.png"};
const iconMarkup=(id,className="char-icon")=>ICON_PATHS[id]?`<img class="${className}" src="${ICON_PATHS[id]}" alt="" aria-hidden="true">`:"";
const MINA_THEME_PATH="assets/jegal-mina-theme.css";
if(!document.querySelector('link[data-seonga-jegal-mina-theme]')){const link=document.createElement("link");link.rel="stylesheet";link.href=MINA_THEME_PATH;link.dataset.seongaJegalMinaTheme="";document.head.append(link);}

const cast=()=>[...state.partyIds,state.supportId].filter((id,index,all)=>all.indexOf(id)===index);

function presentationMarkup(){
  if(!activePresentation)return"";const x=activePresentation,kind=x.type||"narration",commonTone=["damage","danger","success","warning"].includes(x.tone),accentId=x.accent||(!commonTone&&E.characterPool.includes(x.source)?x.source:""),accent=accentId?` accent-${accentId}`:"",tone=x.tone?` tone-${x.tone}`:"",body=kind==="effect"&&x.items?`<ul>${x.items.map(item=>`<li>${item.text}</li>`).join("")}</ul>`:`<strong>${kind==="dialogue"?`“${x.text}”`:x.text}</strong>`;
  return`<aside class="presentation-layer ${kind}${accent}${tone}" aria-live="assertive">${kind==="dialogue"?iconMarkup(accentId,"presentation-watermark"):""}<span class="presentation-kind">${kind==="dialogue"?x.speaker:kind==="effect"?"RESULT":"SCENE"}</span><div class="presentation-body">${body}</div><button type="button" class="presentation-next" data-action="presentation-next">${kind==="dialogue"?"계속":"빠르게 넘기기"} <b>›</b></button></aside>`;
}
function bundlePresentation(events){const bundled=[];for(const item of events){const previous=bundled[bundled.length-1];if(item.type==="effect"&&previous?.type==="effect"){previous.items.push(item);previous.text=previous.items.map(x=>x.text).join(" · ");if(["danger","damage"].includes(item.tone))previous.tone=item.tone;}else bundled.push(item.type==="effect"?{...item,items:[item]}:item);}return bundled;}
function presentationDelay(item){return item.type==="narration"?720:560;}
function advancePresentation(){if(presentationTimer)clearTimeout(presentationTimer);presentationTimer=null;if(!presentationQueue.length){activePresentation=null;inputLocked=false;render();return;}activePresentation=presentationQueue.shift();render();if(activePresentation.type!=="dialogue")presentationTimer=setTimeout(advancePresentation,presentationDelay(activePresentation));}
function playPresentation(){presentationQueue.push(...bundlePresentation(LibraryEngine.takePresentation(state)));if(window.SEONGA_TEST_INSTANT_PRESENTATION){presentationQueue.length=0;activePresentation=null;inputLocked=false;render();return;}if(inputLocked||!presentationQueue.length){render();return;}inputLocked=true;advancePresentation();}
function flushPresentation(){if(presentationTimer)clearTimeout(presentationTimer);presentationQueue.length=0;LibraryEngine.takePresentation(state);activePresentation=null;inputLocked=false;render();}
function render(){const views={party:renderParty,briefing:renderBriefing,exploration:renderExploration,battle:renderBattle,success:renderResult,failure:renderResult};app.innerHTML=presentationMarkup()+views[state.phase]();}

function renderParty(){
  const pool=E.characterPool.map(LibraryEngine.character),support=LibraryEngine.character(state.supportId);
  const roster=pool.map((c,i)=>{const selected=state.partyIds.includes(c.id),rear=c.id===state.supportId;return`<button type="button" class="roster-row accent-${c.id} ${selected?"selected":""} ${rear?"rear":""}" data-action="toggle:${c.id}" aria-pressed="${selected}" ${inputLocked?"disabled":""}><span class="roster-index">${String(i+1).padStart(2,"0")}</span><span class="roster-emblem">${iconMarkup(c.id,"roster-icon")}</span><span class="roster-name"><strong>${c.name}</strong><small>${c.game.position}열 · ${c.game.role}</small></span><span class="roster-state">${selected?"출전":"대기"}</span></button>`;}).join("");
  const rear=pool.filter(c=>!state.partyIds.includes(c.id)).map(c=>`<button type="button" class="support-pick accent-${c.id} ${c.id===state.supportId?"selected":""}" data-action="support-select:${c.id}" ${inputLocked?"disabled":""}><strong class="icon-label">${iconMarkup(c.id,"support-pick-icon")}<span>${c.name}</span></strong><small>${E.supportAdapters[c.id].label}</small></button>`).join("");
  return`<main class="formation-screen"><header class="screen-heading"><p class="chapter">INCIDENT 03 · DEPLOYMENT</p><h1>도서관에 데려갈 네 명</h1><p>명단을 눌러 출전을 정하고, 남은 인원 가운데 후방 담당을 지정한다.</p></header><div class="formation-layout"><section class="roster-list" aria-label="출전 명단">${roster}</section><aside class="formation-summary"><p class="eyebrow">CURRENT UNIT · ${state.partyIds.length}/${E.rules.partySize}</p><div class="party-ribbon">${state.partyIds.map((id,i)=>`<span class="accent-${id}">${iconMarkup(id,"ribbon-icon")}<b>${i+1}</b>${LibraryEngine.character(id).name}</span>`).join("")}</div><p class="eyebrow">REAR SUPPORT</p><div class="support-picks">${rear}</div><p class="support-brief accent-${support.id}"><strong class="icon-label">${iconMarkup(support.id,"label-icon")}<span>${support.name}</span></strong>${E.supportAdapters[support.id].description}</p>${button("편성 확정","briefing",state.partyIds.length!==E.rules.partySize,"브리핑으로 이동한다.",true)}</aside></div></main>`;
}
function renderBriefing(){return`<main class="story-screen"><p class="chapter">INCIDENT 03 · BRIEFING</p><h1>${E.title}</h1><p class="story-copy">${E.briefing}</p><div class="mina-notice accent-jegal-mina"><strong class="icon-label">${iconMarkup("jegal-mina","label-icon")}<span>제갈 미나 · 현장 협조자</span></strong><span>“${E.dialogue.mina.briefing}”</span><small>※ 제갈 미나는 부정확한 정보를 제공할 수 있습니다. 실제 결과는 책임지지 않습니다.</small></div><div class="dialogue-list compact">${cast().map(id=>{const c=LibraryEngine.character(id);return`<blockquote class="accent-${id} ${id===state.supportId?"off-field":""}">${iconMarkup(id,"speaker-watermark")}<strong class="speaker-tag"><span>${c.name}${id===state.supportId?" · 후방":""}</span></strong><span>“${E.dialogue.briefing[id]}”</span></blockquote>`;}).join("")}</div><footer class="story-command">${button("사전 조사 시작 →","begin-explore",false,"",true)}</footer></main>`;}

function statusLabel(id){const status=LibraryEngine.factStatus(state,id);if(status==="locked")return"고정됨";if(status==="verified")return"검증됨";if(status==="misverified")return"오판";return LibraryEngine.canJudgeFact(state,id)?"판정 가능":"미확정";}
function factSummaryMarkup(withActions=false){return`<div class="fact-line">${Object.entries(E.facts).map(([id,f])=>{const status=LibraryEngine.factStatus(state,id),conflict=LibraryEngine.factConflict(state,id),options=LibraryEngine.claimOptions(state,id);return`<article class="fact-card ${status}"><span>${f.label}</span><strong>현재 주장 · ${state.facts[id].current}</strong><small>${statusLabel(id)}${state.facts[id].playerClaim?` · 내 판정 ${state.facts[id].playerClaim}`:""}${status==="verified"?" · 현실은 아직 오염 가능":""}</small>${conflict.observations.length?`<small>충돌 관측 · ${conflict.observations.join(" / ")}</small>`:""}${withActions&&options.length?`<small>판정 선택지는 해결 구간 COMMAND에서 열린다. 판단 보류 가능.</small>`:""}</article>`;}).join("")}</div>`;}
function evidenceList(){const ids=Object.keys(state.evidence);return ids.length?ids.map(id=>{const ev=state.evidence[id],info=E.evidenceInfo[id],marks=[info.qualityLabel,ev.protected?"보호됨":null,ev.authoritative?"공식 기준점":null,ev.enhancementInteractionUsed||ev.comparisonInteractions?.length?"관계 사용":null].filter(Boolean).join(" · ");return`<li><strong>${info.label}</strong><span>${marks}<br>${info.summary}</span></li>`;}).join(""):"<li class=\"muted\">아직 확보한 증거가 없다.</li>";}
function renderInteraction(item){return`<main class="story-screen interaction-screen"><p class="chapter">RELATIONSHIP INTERACTION · [GAME]</p><h1>${item.title}</h1><p class="story-copy">${item.prompt}</p><div class="interaction-options">${button(item.applyLabel,"interaction:apply",false,item.applyDescription,true)}${button(item.skipLabel,"interaction:skip",false,"추가 효과 없이 현재 증거만 유지한다.")}</div></main>${renderLog()}`;}
function renderExploration(){
  const pending=LibraryEngine.currentInteraction(state);if(pending)return renderInteraction(pending);
  if(state.selectedLocation){const location=E.investigations.find(x=>x.id===state.selectedLocation);return`<main class="investigation-screen approach-stage"><header class="screen-heading"><p class="chapter">FIELD APPROACH · ${E.rules.investigationLimit-state.investigationsLeft+1}/${E.rules.investigationLimit}</p><h1>${location.label}</h1><p>${location.prompt}</p></header><p class="approach-prompt">어느 절반의 증거를 먼저 확보할까?</p><div class="approach-list">${location.choices.map(choice=>{const c=LibraryEngine.character(choice.owner);return`<button type="button" class="approach-choice accent-${c.id}" data-action="investigate:${choice.id}" ${inputLocked?"disabled":""}><span class="approach-who">${iconMarkup(c.id,"approach-icon")}<span>${c.name}</span></span><strong>${choice.label}</strong><span>${choice.approach}</span><em>예상 · ${choice.expectation}</em></button>`;}).join("")}</div><nav class="quiet-command">${button("← 다른 장소 보기","leave-location")}</nav></main>${renderLog()}`;}
  const available=E.investigations.filter(x=>!state.investigated.includes(x.id));
  return`<main class="investigation-screen location-stage"><header class="screen-heading"><p class="chapter">INCIDENT 03 · EVIDENCE SURVEY</p><h1>다섯 기록 중 세 곳</h1><p>같은 지점의 두 접근법은 동시에 택할 수 없다. 초기 조사에서는 사실을 잠글 수 없으며, 누락된 핵심 증거는 해결 구간에서 복구한다.</p></header><div class="investigation-meter"><strong>남은 조사 <b>${state.investigationsLeft}</b>회</strong><span>${state.investigated.map(id=>E.investigations.find(x=>x.id===id).label).join(" · ")||"조사 전"}</span></div><div class="scene-list">${available.map((x,i)=>`<button type="button" class="scene-choice" data-action="select-location:${x.id}" ${state.investigationsLeft<=0||inputLocked?"disabled":""}><span>${String(i+1).padStart(2,"0")}</span><strong>${x.label}</strong><small>${x.prompt}</small><i>살펴보기 →</i></button>`).join("")}</div><aside class="evidence-strip"><p class="eyebrow">FOUND EVIDENCE · 확보 증거 ${Object.keys(state.evidence).length}/${E.rules.investigationLimit}</p><ul>${evidenceList()}</ul></aside><section class="fact-board"><p class="eyebrow">FACT VERIFICATION</p>${factSummaryMarkup(true)}</section><div class="dual-meter"><div><span>현실 안정도</span><strong>${state.stability}/${E.rules.maxStability}</strong></div><div><span>미나 처리 부하</span><strong>${state.minaLoad}/${E.rules.maxMinaLoad}</strong></div></div><footer class="story-command">${button("사건 대응을 시작한다 →","start",state.investigated.length!==E.rules.investigationLimit,state.investigated.length!==E.rules.investigationLimit?"서로 다른 장소 세 곳을 조사해야 한다.":"",true)}</footer></main>${renderLog()}`;
}

function memberResource(id,m){if(id==="hwayoung")return`열량 ${m.heat}`;if(id==="kang-unshim")return`정보 ${m.info}`;if(id==="epi-minos")return`보존 ${m.memory}`;if(id==="inan"||id==="kim-wooju")return m.cool?"재정비":"능력 준비";if(id==="mageuna")return`집행 ${m.rules}/3`;if(id==="josangmin")return`비축 ${m.effort}`;return"침식 주의";}
function commandMarkup(actor,actions){const abilities=new Set((E.abilities[actor.id]||[]).map(a=>a.id));return actions.map(a=>{const isAbility=abilities.has(a.id);return`<button type="button" class="action-button accent-${actor.id} ${isAbility?"ability-command":"field-command"}" data-action="act:${a.id}" ${a.disabled||inputLocked?"disabled":""}>${isAbility?iconMarkup(actor.id,"command-character-icon"):""}<span class="command-copy"><strong>${a.label}</strong><small>${a.description}</small></span></button>`;}).join("");}
function patternTarget(p){if(Object.hasOwn(p,"known")){if(!p.known)return"표적 비공개";return E.facts[p.target]?.label||({system:"시스템 자료",record:"공식 기록",archive:"보존 장면"}[p.target]||p.target);}let target="미고정 사실";if(p.fact)target=E.facts[p.fact].label;else if(p.kind)target=({system:"시스템 자료",record:"공식 기록",archive:"보존 장면"}[p.kind]||p.kind);const order=state.lockOrder.length?state.lockOrder.map(id=>E.facts[id].label.slice(0,2)).join("→"):"없음";return`${target} · ${state.battlePhase.toUpperCase()} · 고정 순서 ${order}`;}
function recoveryMarkup(){const rows=Object.keys(E.facts).filter(id=>LibraryEngine.missingAnchors(state,id).length);return rows.length?`<div class="recovery-list">${rows.map(id=>`<div><strong>${E.facts[id].label} 재조사</strong><span>누락 핵심 증거 ${LibraryEngine.missingAnchors(state,id).length}건 · 사용 ${state.reinvestigations[id]}/${E.rules.maxReinvestigationsPerFact}</span></div>`).join("")}</div>`:`<p class="hint">잠금에 필요한 핵심 증거가 모두 확보됐다.</p>`;}
function renderBattle(){
  const actor=LibraryEngine.character(state.order[state.turn]),support=LibraryEngine.character(state.supportId),pattern=LibraryEngine.currentPattern(state),next=LibraryEngine.patternForecast(state);
  const party=state.partyIds.map(id=>{const c=LibraryEngine.character(id),m=state.members[id],width=Math.round(m.hp/c.game.hp*100);return`<div class="member accent-${id} ${id===actor.id?"active":""} ${m.hp===0?"incapacitated":""}"><strong class="member-name">${iconMarkup(id,"member-icon")}<span>${c.name}${m.hp===0?" · 전투 불능":""}</span></strong><div class="hp-bar"><i style="width:${width}%"></i></div><small>${m.hp}/${c.game.hp} HP · <b class="resource-value">${memberResource(id,m)}</b></small></div>`;}).join("");
  const supportAdapter=E.supportAdapters[state.supportId],supportStatus=LibraryEngine.supportStatus(state),supportRule=state.supportId==="mageuna"?` · 집행 ${state.members.mageuna.rules}/3`:"";
  return`<main class="combat-screen ${state.stability<=3?"high-threat":""}"><div class="stage-track">${Object.keys(E.facts).map((id,i)=>`<span class="${LibraryEngine.factStatus(state,id)==="locked"?"done":LibraryEngine.factStatus(state,id)==="verified"?"current":""}">${i+1}. ${E.facts[id].label.replace(/^F\d · /,"")} · ${statusLabel(id)}</span>`).join("")}</div><header class="actor-focus accent-${actor.id}">${iconMarkup(actor.id,"actor-watermark")}<div class="actor-copy"><p>현실 원본 복구 · ROUND ${state.round}</p><h1>${actor.name}</h1><span>${actor.game.role} · 행동을 선택한다</span></div></header><section class="danger-line"><div><span>현실 안정도</span><strong>${state.stability}<small>/${E.rules.maxStability}</small></strong></div><p><b>${pattern.label} · ${patternTarget(pattern)}</b>${pattern.description}<small>다음 오류 · ${next.label} · ${patternTarget(next)}</small></p><div><span>미나 부하</span><strong>${state.minaLoad}<small>/${E.rules.maxMinaLoad}</small></strong></div></section><section class="mission-line"><p class="eyebrow">IMMEDIATE OBJECTIVE</p><strong>사실 고정 <b>${LibraryEngine.lockedCount(state)}/3</b></strong><span>${LibraryEngine.lockedCount(state)===2?"마지막 사실의 핵심 증거를 완성해 ‘정답 강제’를 실행한다.":"누락된 핵심 증거를 복구하고 검증된 사실을 현재 현실에 고정한다."}</span>${state.minaOfflineRounds?"<em>미나 블루스크린 · 현실 고정 일시 중단</em>":state.rewriteBlock?"<em>정정 제한 · 다음 재작성 차단 대기</em>":""}</section><section class="command-section accent-${actor.id}"><p class="eyebrow">COMMAND</p><div class="command-menu">${commandMarkup(actor,LibraryEngine.actions(state))}</div></section><section class="field-state fact-board"><p class="eyebrow">FACT STATUS</p>${factSummaryMarkup(false)}<p class="eyebrow recovery-heading">ANCHOR RECOVERY</p>${recoveryMarkup()}</section><section class="party-status"><p class="eyebrow">FIELD UNIT</p><div class="party-status-rail">${party}</div></section><section class="evidence-ledger"><p class="eyebrow">EVIDENCE LEDGER</p><ul>${Object.keys(state.evidence).map(id=>{const ev=state.evidence[id],active=LibraryEngine.evidenceActive(state,id);return`<li class="${active?"":"disabled"}"><strong>${E.evidenceInfo[id].label}</strong><span>${E.evidenceInfo[id].qualityLabel}${ev.protected?" · 보호됨":""}${ev.authoritative?" · 공식 기준점":""}${active?"":" · 출처 소실"}</span></li>`;}).join("")}</ul></section><section class="support-call accent-${support.id}"><div><p class="eyebrow">REAR SUPPORT · 사건 전체 ${state.supportUses}/${E.rules.supportCharges}${supportRule}</p><strong class="icon-label">${iconMarkup(support.id,"support-icon")}<span>${support.name} · ${supportAdapter.label}</span></strong><span>${supportAdapter.description}</span><small>${supportStatus.available?"지금 연결 가능":supportStatus.reason}</small></div>${button("후방 지원 요청","support",!supportStatus.available)}</section><aside class="mina-status accent-jegal-mina"><strong class="icon-label">${iconMarkup("jegal-mina","label-icon")}<span>제갈 미나 · 현장 협조자</span></strong><span>“${LibraryEngine.minaReaction(state)}”</span></aside></main>${renderLog()}`;
}

function renderResult(){const success=state.phase==="success";if(success&&!state.recorded&&window.CampaignProgress){CampaignProgress.complete(E.id,LibraryEngine.resultSummary(state));state.recorded=true;}const order=state.lockOrder.map(id=>E.facts[id].label.slice(0,2)).join("→")||"없음",resultText=success?`세 사실 고정 완료 · 순서 ${order} · 오판 ${state.misjudgments}회`:state.failureReason;return`<main class="ending-screen ${success?"success":"failure"}"><p class="chapter">INCIDENT RESULT</p><h1>${success?"도서관 원본 복구 완료":"대응 실패"}</h1><p class="result-line">${resultText}</p>${success?`<div class="mina-notice accent-jegal-mina"><strong class="icon-label">${iconMarkup("jegal-mina","label-icon")}<span>제갈 미나</span></strong><span>“현재 도서관은 정상 운영 중입니다. …이번 문장은 정말 맞습니다.”</span></div><div class="dialogue-list compact">${cast().map(id=>`<blockquote class="accent-${id} ${id===state.supportId?"off-field":""}">${iconMarkup(id,"speaker-watermark")}<strong class="speaker-tag"><span>${LibraryEngine.character(id).name}${id===state.supportId?" · 후방":""}</span></strong><span>“${E.dialogue.ending[id]}”</span></blockquote>`).join("")}</div>`:""}<dl class="result-stats"><div><dt>고정 순서</dt><dd>${order}</dd></div><div><dt>오판</dt><dd>${state.misjudgments}회</dd></div><div><dt>남은 안정도</dt><dd>${state.stability}/${E.rules.maxStability}</dd></div><div><dt>미나 부하</dt><dd>${state.minaLoad}/${E.rules.maxMinaLoad}</dd></div></dl><nav class="ending-commands"><a class="action-button" href="index.html"><strong>지도부실로</strong></a>${button("다른 선택으로 재시작","reset",false,"",true)}</nav></main>${renderLog()}`;}

function logItem(x){const type=x.type||"narration",commonTone=["damage","danger","success","warning","recover","guard"].includes(x.tone),accentId=x.accent||(!commonTone&&E.characterPool.includes(x.source)?x.source:""),accent=accentId?` accent-${accentId}`:"",tone=x.tone?` tone-${x.tone}`:"";if(type==="dialogue")return`<li class="dialogue${accent}${tone}"><strong>${x.speaker}</strong><span>“${x.text}”</span></li>`;return`<li class="${type}${accent}${tone}"><span>${x.text||x.message}</span></li>`;}
function renderLog(){return`<details class="log-panel"><summary>대응 기록 <small>${state.log.length}건 · 펼쳐 보기</small></summary><ol>${state.log.slice().reverse().map(logItem).join("")}</ol></details>`;}

app.addEventListener("click",event=>{let target=event.target;while(target&&target!==app&&!target.dataset.action)target=target.parentElement;if(!target||target===app)return;const raw=target.dataset.action,separator=raw.indexOf(":"),type=separator<0?raw:raw.slice(0,separator),id=separator<0?"":raw.slice(separator+1);if(type==="presentation-next"&&inputLocked){advancePresentation();return;}if(inputLocked)return;let changed=false;if(type==="toggle")changed=LibraryEngine.toggle(state,id);if(type==="support-select")changed=LibraryEngine.support(state,id);if(type==="briefing")changed=LibraryEngine.beginBriefing(state);if(type==="begin-explore")changed=LibraryEngine.beginExplore(state);if(type==="select-location")changed=LibraryEngine.selectLocation(state,id);if(type==="leave-location")changed=LibraryEngine.leaveLocation(state);if(type==="investigate")changed=LibraryEngine.investigate(state,id);if(type==="interaction")changed=LibraryEngine.resolveInteraction(state,id==="apply");if(type==="compare")changed=LibraryEngine.compareEvidence(state,id);if(type==="start")changed=LibraryEngine.start(state);if(type==="act")changed=LibraryEngine.act(state,id);if(type==="support")changed=LibraryEngine.useSupport(state);if(type==="reset"){state=LibraryEngine.create();changed=true;}if(changed)playPresentation();else render();});
window.SEONGA_LIBRARY_UI_DEBUG={isLocked:()=>inputLocked,getState:()=>state,flushPresentation};
render();
