"use strict";

window.MagnumEngine=(()=>{
  const E=SEONGA_MAGNUM_EVENT,C=SEONGA_CHARACTERS,B=E.balance;
  const character=id=>C.find(x=>x.id===id),member=(s,id)=>s.members[id];
  function present(s,type,text,meta={}){const item={type,text,message:text,...meta};s.log.push(item);s.presentation.push(item);return item;}
  const dialogue=(s,text,speaker,meta={})=>present(s,"dialogue",text,{speaker,...meta});
  const narration=(s,text,meta={})=>present(s,"narration",text,meta);
  const effect=(s,text,meta={})=>present(s,"effect",text,meta);
  const aliveIds=s=>s.partyIds.filter(id=>member(s,id).hp>0);
  const currentId=s=>s.order[s.turn];
  const availableCharacterIds=()=>[...E.characterPool];
  const mirrorAmount=amount=>Math.max(1,Math.round(amount*B.mirrorRatio));

  function create(){
    const members={};C.forEach(x=>members[x.id]={hp:x.game.hp,guard:0,heat:0,info:0,memory:0,cool:0,effort:0,rules:SEONGA_NEUTRAL_KITS[x.id]?.limit||0});
    return{phase:"party",partyIds:["hwayoung","kang-unshim","inan","kim-wooju"],supportId:"byeon-ari",members,investigated:[],selectedLocation:null,investigationsLeft:E.rules.investigationLimit,clues:[],rewards:{forecastDetail:false,initialInstability:0,reconstructionReduction:0,copyCancelCharges:0,mirrorDampenCharges:0},magnum:{hp:B.magnumMaxHp,maxHp:B.magnumMaxHp,instability:0,maxInstability:B.instabilityMax,phase:"imitation",copyQueue:null,lastCopiedActor:null,lastCopiedAbility:null,reconstructed:false,shattered:false,shield:0},round:1,order:[],turn:0,acted:[],supportUses:E.rules.supportCharges,supportUsedRound:0,bossTargetIndex:0,bossAttackBlock:false,bossAttackBonus:0,vulnerability:0,mirroredAbilitySeal:null,stageActions:0,failureReason:"",log:[],presentation:[]};
  }
  function toggle(s,id){const pool=availableCharacterIds();if(s.phase!=="party"||!pool.includes(id))return false;const index=s.partyIds.indexOf(id);if(index>=0){if(s.partyIds.length<=1)return false;s.partyIds.splice(index,1);}else if(s.partyIds.length<E.rules.partySize)s.partyIds.push(id);else return false;if(s.partyIds.includes(s.supportId)){const replacement=pool.find(x=>!s.partyIds.includes(x));if(replacement)s.supportId=replacement;}return true;}
  function support(s,id){if(s.phase!=="party"||s.partyIds.includes(id)||!availableCharacterIds().includes(id))return false;s.supportId=id;return true;}
  function beginBriefing(s){if(s.partyIds.length!==E.rules.partySize||s.partyIds.includes(s.supportId))return false;s.phase="briefing";return true;}
  function beginExplore(s){if(!["party","briefing"].includes(s.phase)||s.partyIds.length!==E.rules.partySize)return false;s.phase="exploration";return true;}
  function selectLocation(s,id){if(s.phase!=="exploration"||s.investigationsLeft<=0||s.investigated.includes(id)||!E.investigations.some(x=>x.id===id))return false;s.selectedLocation=id;return true;}
  function leaveLocation(s){if(s.phase!=="exploration")return false;s.selectedLocation=null;return true;}
  function applyClue(s,clue){if(clue==="mirror-profile")s.rewards.forecastDetail=true;if(clue==="unstable-seam")s.rewards.initialInstability++;if(clue==="reconstruction-scar")s.rewards.reconstructionReduction=B.reconstructionHpReduction;if(clue==="copy-cut")s.rewards.copyCancelCharges++;}
  function investigate(s,choiceId){if(s.phase!=="exploration"||!s.selectedLocation||s.investigationsLeft<=0)return false;const location=E.investigations.find(x=>x.id===s.selectedLocation),choice=location?.choices.find(x=>x.id===choiceId);if(!choice)return false;s.clues.push(choice.clue);s.investigated.push(location.id);s.investigationsLeft--;s.selectedLocation=null;applyClue(s,choice.clue);narration(s,`${location.label}에서 ${character(choice.owner).name}의 조사가 시작된다.`,{accent:choice.owner});dialogue(s,choice.quote,character(choice.owner).name,{accent:choice.owner});narration(s,choice.result,{accent:choice.owner});effect(s,`단서 확보 · ${E.clueInfo[choice.clue].label}`,{source:choice.owner,stat:"clue"});return true;}
  function buildOrder(s){s.order=aliveIds(s).sort((a,b)=>character(b).game.speed-character(a).game.speed);s.turn=0;s.acted=[];}
  function start(s){if(s.phase!=="exploration"||s.investigated.length!==E.rules.investigationLimit)return false;s.phase="battle";s.round=1;s.magnum.instability=s.rewards.initialInstability;buildOrder(s);narration(s,"대피가 끝난 체육관 중앙에서 서로 다른 천사의 날개와 얼굴이 한 몸 위로 겹쳐 움직인다.",{tone:"transition"});dialogue(s,E.dialogue.boss.opening,"매그넘",{accent:"magnum"});if(s.magnum.instability)effect(s,`초기 불안정 +${s.magnum.instability}`,{stat:"instability",delta:s.magnum.instability,tone:"warning"});return true;}

  function damageBoss(s,amount,source){if(s.magnum.shattered)return 0;let actual=amount;if(s.magnum.shield){const blocked=Math.min(actual,s.magnum.shield);s.magnum.shield-=blocked;actual-=blocked;if(blocked)effect(s,`매그넘 방호 -${blocked}`,{stat:"bossShield",delta:-blocked,tone:"guard"});}if(s.vulnerability&&actual){actual+=s.vulnerability;s.vulnerability=0;}s.magnum.hp=Math.max(0,s.magnum.hp-actual);if(actual)effect(s,`매그넘 HP -${actual} · ${s.magnum.hp}/${s.magnum.maxHp}`,{source,stat:"bossHp",delta:-actual,tone:"damage"});resolveBossHp(s);return actual;}
  function healBoss(s,amount){const before=s.magnum.hp;s.magnum.hp=Math.min(s.magnum.maxHp,s.magnum.hp+amount);const gain=s.magnum.hp-before;if(gain)effect(s,`매그넘 HP +${gain} · ${s.magnum.hp}/${s.magnum.maxHp}`,{stat:"bossHp",delta:gain,tone:"recover"});}
  function enterCollapse(s){if(s.magnum.phase!=="imitation"||s.magnum.shattered)return;s.magnum.phase="collapse";narration(s,"등의 깃털이 뿌리부터 갈라지고 금테 안경 아래의 검은 X자 동공이 서로 다른 속도로 흔들린다.",{tone:"danger"});dialogue(s,E.dialogue.boss.collapse,"매그넘",{accent:"magnum",tone:"danger"});effect(s,"PHASE 2 · 형상 붕괴",{stat:"bossPhase",tone:"warning"});}
  function shatter(s,reason){if(s.magnum.shattered)return false;s.magnum.shattered=true;s.magnum.phase="shattered";s.magnum.copyQueue=null;narration(s,"겹쳐 있던 얼굴들이 한꺼번에 어긋나고, 앙상한 날개 사이로 매그넘의 본래 윤곽이 드러난다.",{tone:"danger"});dialogue(s,E.dialogue.boss.shatter,"매그넘",{accent:"magnum",tone:"danger"});effect(s,`미러링 파열 · ${reason}`,{stat:"shattered",tone:"success"});return true;}
  function increaseInstability(s,amount,source="copy"){if(s.magnum.shattered)return;s.magnum.instability=Math.min(s.magnum.maxInstability,s.magnum.instability+amount);effect(s,`복제 불안정 +${amount} · ${s.magnum.instability}/${s.magnum.maxInstability}`,{source,stat:"instability",delta:amount,tone:"warning"});if(s.magnum.instability>=s.magnum.maxInstability)shatter(s,"불안정 한계");else if(s.magnum.instability>=B.collapseThreshold)enterCollapse(s);}
  function resolveBossHp(s){if(s.magnum.hp>0||s.magnum.shattered)return;if(!s.magnum.reconstructed){s.magnum.reconstructed=true;s.magnum.phase="collapse";s.magnum.copyQueue=null;const recovered=Math.max(1,Math.ceil(s.magnum.maxHp*B.reconstructionHpRatio)-s.rewards.reconstructionReduction);s.magnum.hp=recovered;narration(s,"천사 모사 외형이 바닥으로 쏟아진 뒤, 남은 살과 깃이 오른쪽 다리를 중심으로 다시 사람의 형태를 세운다.",{tone:"danger"});dialogue(s,E.dialogue.boss.reconstruct,"매그넘",{accent:"magnum",tone:"danger"});effect(s,`신체 재구성 · HP ${recovered}/${s.magnum.maxHp}`,{stat:"reconstructed",tone:"warning"});increaseInstability(s,B.reconstructionInstabilityGain,"reconstruction");}else shatter(s,"재구성 붕괴");}
  function damageMember(s,id,amount,source="magnum"){const m=member(s,id);if(!m||m.hp<=0)return 0;let actual=amount;if(m.guard){const blocked=Math.min(actual,m.guard);m.guard-=blocked;actual-=blocked;if(blocked)effect(s,`${character(id).name} 방호 -${blocked}`,{source:id,stat:"guard",delta:-blocked,tone:"guard"});}m.hp=Math.max(0,m.hp-actual);if(actual)effect(s,`${character(id).name} HP -${actual} · ${m.hp}`,{source,stat:"hp",delta:-actual,tone:"damage"});if(m.hp===0)effect(s,`${character(id).name} 전투 불능`,{source:id,stat:"incapacitated",tone:"danger"});return actual;}
  function healMember(s,id,amount){const m=member(s,id),max=character(id).game.hp,before=m.hp;m.hp=Math.min(max,m.hp+amount);const gain=m.hp-before;if(gain)effect(s,`${character(id).name} HP +${gain} · ${m.hp}`,{source:id,stat:"hp",delta:gain,tone:"recover"});}
  function weakestId(s){return aliveIds(s).sort((a,b)=>member(s,a).hp/character(a).game.hp-member(s,b).hp/character(b).game.hp||s.partyIds.indexOf(a)-s.partyIds.indexOf(b))[0];}
  function nextTarget(s){const alive=aliveIds(s);if(!alive.length)return null;const id=alive[s.bossTargetIndex%alive.length];s.bossTargetIndex++;return id;}

  const MIRROR_ADAPTERS={
    absorbThreat(s,q,p){s.magnum.shield+=p;const target=nextTarget(s);if(target)damageMember(s,target,1);},
    gatherIntel(s,q,p){s.bossAttackBonus+=p;},
    snapshotState(s,q,p){healBoss(s,p);},restoreState(s,q,p){healBoss(s,p);},stabilizeField(s,q,p){healBoss(s,p);},
    analyze(s,q,p){s.bossAttackBonus+=p;},
    declareRule(s,q,p){s.mirroredAbilitySeal={actorId:q.actorId,abilityId:q.abilityId,untilRound:s.round+1};const target=nextTarget(s);if(target)damageMember(s,target,p);},
    purify(s,q,p){const target=nextTarget(s);if(target)damageMember(s,target,p);},
    conserveAction(s,q,p){s.magnum.shield+=p;effect(s,`매그넘 방호 +${p}`,{stat:"bossShield",delta:p,tone:"guard"});},
    decisiveIntervention(s,q,p){const target=nextTarget(s);if(target)damageMember(s,target,p);},
    overwriteReality(s,q,p){healBoss(s,p);aliveIds(s).forEach(id=>damageMember(s,id,1));},
    envyStrike(s,q,p){const target=nextTarget(s);if(target)damageMember(s,target,p);}
  };
  function queueCopy(s,actorId,ability){s.magnum.copyQueue={actorId,abilityId:ability.id,verb:ability.verb,power:ability.power||1,label:ability.label};narration(s,`매그넘의 날개가 ${character(actorId).name}의 자세를 뒤늦게 따라 접힌다.`,{accent:"magnum"});effect(s,`복제 대기 · ${character(actorId).name} / ${ability.label.split(" · ").pop()}`,{source:actorId,stat:"copyQueue",tone:"warning"});}
  function executeCopy(s){const q=s.magnum.copyQueue;if(!q)return false;const changed=s.magnum.lastCopiedActor!==null&&(s.magnum.lastCopiedActor!==q.actorId||s.magnum.lastCopiedAbility!==q.abilityId);let power=mirrorAmount(q.power);if(s.rewards.mirrorDampenCharges>0){power=Math.max(1,power-1);s.rewards.mirrorDampenCharges--;effect(s,"복제 효과 약화",{stat:"mirrorDampen",tone:"guard"});}narration(s,`매그넘의 얼굴 위로 ${character(q.actorId).name}의 눈과 자세가 어설프게 겹쳐 올라온다.`,{accent:"magnum",tone:"danger"});dialogue(s,"그거 좋아 보이네. 이제 내 거야.","매그넘",{accent:"magnum"});MIRROR_ADAPTERS[q.verb](s,q,power);s.magnum.lastCopiedActor=q.actorId;s.magnum.lastCopiedAbility=q.abilityId;s.magnum.copyQueue=null;let gain=B.copyInstabilityBase+(changed?B.copySwitchBonus:0)+(q.actorId==="mageuna"?B.mageunaCopyBonus:0);increaseInstability(s,gain,q.actorId);if(s.magnum.phase==="collapse"&&!s.magnum.shattered&&member(s,q.actorId)?.hp>0){narration(s,`${character(q.actorId).name}의 동작을 베낀 관절이 반대 방향으로 한 번 더 꺾인다. 같은 충격이 원본 쪽으로 되튄다.`,{accent:"magnum",tone:"damage"});damageMember(s,q.actorId,B.collapseEchoDamage,q.actorId);effect(s,`모사 반향 · HP -${B.collapseEchoDamage}`,{source:q.actorId,stat:"hp",tone:"damage"});}return true;}
  function bossAttack(s){if(s.magnum.shattered||s.phase!=="battle")return;if(s.bossAttackBlock){s.bossAttackBlock=false;narration(s,"붉은 철사가 매그넘의 발목을 당겨 다음 도약을 바닥에 묶는다.",{tone:"guard"});effect(s,"매그넘 기본 공격 차단",{stat:"bossAttack",tone:"guard"});s.bossAttackBonus=0;return;}const count=s.magnum.phase==="collapse"?B.collapseTargets:1,damage=(s.magnum.phase==="collapse"?B.collapseDamage:B.imitationDamage)+s.bossAttackBonus;s.bossAttackBonus=0;narration(s,s.magnum.phase==="collapse"?"갈라진 날개가 서로 다른 방향으로 꺾이며 체육관 바닥 두 곳을 동시에 후려친다.":"앙상한 날개가 접혔다 펴지며 가장 가까운 출전 인원에게 매그넘을 밀어낸다.",{tone:"damage"});for(let i=0;i<count;i++){const target=nextTarget(s);if(target)damageMember(s,target,damage);}}
  function bossAction(s){if(s.magnum.shattered||s.phase!=="battle")return false;executeCopy(s);if(!s.magnum.shattered)bossAttack(s);return true;}
  function checkFailure(s){if(aliveIds(s).length)return false;s.phase="failure";s.failureReason="출전 인원이 모두 전투 불능이 되어 체육관에서 철수했다.";narration(s,s.failureReason,{tone:"danger"});effect(s,"대응 실패",{stat:"failure",tone:"danger"});return true;}
  function endRound(s){bossAction(s);s.partyIds.forEach(id=>{member(s,id).guard=0;if(member(s,id).cool>0)member(s,id).cool--;});if(checkFailure(s)||s.phase!=="battle")return;s.round++;buildOrder(s);}
  function advanceTurn(s,actorId){s.acted.push(actorId);if(checkFailure(s)||s.phase!=="battle")return;const remaining=s.order.filter(id=>member(s,id).hp>0&&!s.acted.includes(id));if(remaining.length){s.turn=s.order.indexOf(remaining[0]);return;}endRound(s);}

  const action=(id,label,description,disabled=false)=>({id,label,description,disabled});
  function canPay(m,a){if(a.cost&&!Object.entries(a.cost).every(([key,value])=>(m[key]||0)>=value))return false;if(a.cooldown&&m[a.cooldown]>0)return false;if(a.ruleCost&&m.rules<a.ruleCost)return false;if(a.hpCost&&m.hp<a.hpCost)return false;return true;}
  function actions(s){if(s.phase!=="battle"||!currentId(s))return[];const id=currentId(s),m=member(s,id);if(s.magnum.shattered){const f=E.finishers[id];return[action(`finish:${id}`,f.label,"파열된 미러링을 제압한다.")];}const result=[action("attack","기본 공격","매그넘 HP -2."),action("brace","방호 자세","자신에게 방호 2.")];if(s.rewards.copyCancelCharges>0&&s.magnum.copyQueue)result.push(action("disrupt-copy","빈 프레임 차단",`복제 대기 취소 · 잔여 ${s.rewards.copyCancelCharges}회`));for(const a of E.abilities[id]||[]){let label=a.label;if(id==="epi-minos")label+=` · 보존 ${m.memory}`;if(id==="mageuna")label+=` · 집행 ${m.rules}회`;if(id==="josangmin")label+=` · 비축 ${m.effort}`;const seal=s.mirroredAbilitySeal,sealed=seal&&seal.actorId===id&&seal.abilityId===a.id&&s.round<=seal.untilRound;result.push(action(a.id,label,sealed?`${a.description} · 모사 봉인 중`:a.description,!canPay(m,a)||sealed));}return result;}
  function pay(m,a){if(a.cost)Object.entries(a.cost).forEach(([key,value])=>m[key]-=value);if(a.ruleCost)m.rules-=a.ruleCost;}
  function resolveAbility(s,id,a){const m=member(s,id);if(a.verb==="absorbThreat"){damageBoss(s,2,id);m.guard+=2;m.heat++;}if(a.verb==="gatherIntel"){damageBoss(s,3,id);damageMember(s,id,1,id);m.info++;}if(a.verb==="snapshotState"){damageBoss(s,2,id);m.memory++;}if(a.verb==="restoreState")damageBoss(s,5,id);if(a.verb==="stabilizeField"){const target=weakestId(s);if(target)healMember(s,target,3);m.cool=2;}if(a.verb==="analyze"){damageBoss(s,2,id);s.vulnerability=1;m.cool=2;}if(a.verb==="declareRule"){damageBoss(s,1,id);s.bossAttackBlock=true;}if(a.verb==="purify"){damageBoss(s,4,id);damageMember(s,id,1,id);m.cool=2;}if(a.verb==="conserveAction")m.effort++;if(a.verb==="decisiveIntervention")damageBoss(s,5,id);if(a.verb==="overwriteReality"){s.magnum.shield=0;damageBoss(s,3,id);}if(a.verb==="envyStrike")damageBoss(s,3,id);}
  function finishBoss(s,id){if(s.phase!=="battle"||!s.magnum.shattered||!aliveIds(s).includes(id))return false;const finisher=E.finishers[id];narration(s,finisher.narration,{accent:id,tone:"success"});dialogue(s,finisher.quote,character(id).name,{accent:id,tone:"success"});effect(s,"매그넘 제압 완료",{source:id,stat:"success",tone:"success"});s.phase="success";return true;}
  function act(s,id){if(s.phase!=="battle")return false;const actorId=currentId(s),available=actions(s).find(x=>x.id===id&&!x.disabled);if(!actorId||!available)return false;if(id.startsWith("finish:"))return finishBoss(s,actorId);s.stageActions++;if(id==="attack"){narration(s,`${character(actorId).name}의 공격이 겹쳐 붙은 날개 사이를 친다.`,{accent:actorId});damageBoss(s,2,actorId);}else if(id==="brace"){member(s,actorId).guard+=2;effect(s,`${character(actorId).name} 방호 +2`,{source:actorId,stat:"guard",delta:2,tone:"guard"});}else if(id==="disrupt-copy"){s.rewards.copyCancelCharges--;s.magnum.copyQueue=null;narration(s,"우주가 표시한 빈 프레임에서 매그넘을 향하던 대상 신호가 끊어진다.",{tone:"guard"});effect(s,`복제 대기 취소 · 잔여 ${s.rewards.copyCancelCharges}회`,{stat:"copyQueue",tone:"guard"});}else{const a=(E.abilities[actorId]||[]).find(x=>x.id===id);if(!a)return false;const cues={hwayoung:"화영이 매그넘과 체육관 출구 사이를 몸으로 가로막는다.","kang-unshim":"운심의 화면에 매그넘의 일그러진 얼굴이 연달아 퍼진다.","epi-minos":"카오의 부리 안에서 조금 전의 붕괴 장면이 다시 열린다.",inan:"라파엘의 차가운 촉수가 체육관 바닥을 따라 뻗는다.","kim-wooju":"우주의 드론이 겹쳐진 윤곽 사이에 절단선을 긋는다.",mageuna:"산달폰의 붉은 철사가 마근아의 선언과 함께 천장에서 쏟아진다.","byeon-ari":"가브리엘의 손들이 빌린 깃털을 바깥쪽부터 움켜쥔다.",josangmin:"먐먀의 그림자에서 발톱 하나가 느리게 솟는다.","jegal-mina":"미나의 다이아몬드 동공이 매그넘의 흔들리는 윤곽을 한 점에 맞춘다.",magnum:"두 개의 검은 X자 동공이 서로를 향해 같은 각도로 기울어진다."};narration(s,cues[actorId],{accent:actorId,tone:"ability"});dialogue(s,a.quote,character(actorId).name,{accent:actorId});pay(member(s,actorId),a);const reconstructedBefore=s.magnum.reconstructed;resolveAbility(s,actorId,a);if(!s.magnum.shattered&&s.magnum.reconstructed===reconstructedBefore)queueCopy(s,actorId,a);}if(checkFailure(s)||s.phase!=="battle")return true;advanceTurn(s,actorId);return true;}
  function supportStatus(s){const a=E.supportAdapters[s.supportId],m=member(s,s.supportId);if(s.phase!=="battle")return{available:false,reason:"교전 중이 아니다."};if(s.supportUses<=0)return{available:false,reason:"사건 전체 지원 횟수를 소진했다."};if(s.supportUsedRound===s.round)return{available:false,reason:"이번 라운드에는 이미 지원을 요청했다."};if(a.ruleCost&&m.rules<a.ruleCost)return{available:false,reason:"남은 집행 횟수가 없다."};return{available:true,reason:"사용 가능"};}
  function useSupport(s){const status=supportStatus(s);if(!status.available)return false;const id=s.supportId,a=E.supportAdapters[id],m=member(s,id);s.supportUses--;s.supportUsedRound=s.round;narration(s,`${character(id).name}의 후방 회선이 체육관에 연결된다.`,{accent:id,tone:"support"});dialogue(s,character(id).support?.quote||"지금 끊겠습니다.",`${character(id).name} · 후방`,{accent:id});if(id==="hwayoung")aliveIds(s).forEach(x=>member(s,x).guard++);if(id==="kang-unshim"||id==="magnum")increaseInstability(s,1,id);if(id==="epi-minos"){const target=weakestId(s);if(target)healMember(s,target,2);}if(id==="inan")aliveIds(s).forEach(x=>healMember(s,x,1));if(id==="kim-wooju")s.rewards.mirrorDampenCharges++;if(id==="mageuna"){m.rules--;s.bossAttackBlock=true;}if(id==="byeon-ari"){s.mirroredAbilitySeal=null;damageBoss(s,1,id);}if(id==="josangmin")damageBoss(s,2,id);if(id==="jegal-mina")s.magnum.copyQueue=null;effect(s,`후방 지원 · ${a.label}`,{source:id,stat:"support",tone:"support"});checkFailure(s);return true;}
  function copyForecast(s){const q=s.magnum.copyQueue;if(!q)return{active:false};return{active:true,actorId:q.actorId,actorName:character(q.actorId).name,abilityId:q.abilityId,label:q.label,description:s.rewards.forecastDetail?E.mirrorDescriptions[q.verb]:null};}
  function takePresentation(s){const queued=s.presentation.slice();s.presentation.length=0;return queued;}
  return{create,toggle,support,beginBriefing,beginExplore,selectLocation,leaveLocation,investigate,start,actions,act,useSupport,supportStatus,bossAction,finishBoss,copyForecast,availableCharacterIds,takePresentation,character,event:E,mirrorAdapters:MIRROR_ADAPTERS,_damageBoss:damageBoss,_increaseInstability:increaseInstability,_executeCopy:executeCopy};
})();
